---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_yaus_web }}.yml"
env_file_name: "{{ service_yaus_web }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: yaus-web

docker_port: "{{ service_yaus_web_docker_port }}"
host_port: "{{ service_yaus_web_host_port }}"
image_name: "{{ image_yaus_web_service }}"
tag: "{{ tags_yaus_web_service }}"
replicas: "{{ service_replicas_yaus_web_service }}"
network_alias_name: "{{ network_alias_yaus_web_service }}"
docker_service_stack_name: samarth
docker_service_name: "{{ service_yaus_web }}"
force_reload: "{{ force_reload_yaus_web_service }}"
host_logs_location: "{{ yaus_web_service_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ yaus_web_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"