---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_doc_generator_worker }}.yml"
env_file_name: "{{ service_doc_generator_worker }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: doc_generator_worker_service

#docker_port: "{{ service_doc_generator_worker_docker_port }}"
#host_port: "{{ service_doc_generator_worker_host_port }}"
image_name: "{{ image_doc_generator_worker_service }}"
tag: "{{ tags_doc_generator_worker_service }}"
replicas: "{{ service_replicas_doc_generator_worker_service }}"
network_alias_name: "{{ network_alias_doc_generator_worker_service }}"
docker_service_stack_name: samarth
docker_service_name: "{{ service_doc_generator_worker }}"
force_reload: "{{ force_reload_doc_generator_worker_service }}"
host_logs_location: "{{ doc_generator_worker_logs }}"
docker_logs_location: /logs

DOCKER_HUB_IMAGE: samagragovernance/doc-generator:{{ tag }}

# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ doc_generator_worker_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"