---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_odk_uci_adapter_service }}.yml"
env_file_name: "{{ service_odk_uci_adapter_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: odk_uci_adapter

docker_port: "{{ service_odk_uci_adapter_docker_port }}"
host_port: "{{ service_odk_uci_adapter_host_port }}"
host_port_hasura: "{{ service_odk_uci_adapter_host_port_hasura }}"
host_port_redis_ui: "{{ service_odk_uci_adapter_host_port_redis_ui }}"
image_name: "{{ image_odk_uci_adapter_service }}"
tag: "{{ tags_odk_uci_adapter_service }}"
replicas: "{{ service_replicas_odk_uci_adapter_service }}"
network_alias_name: "{{ network_alias_odk_uci_adapter_service }}"
docker_service_stack_name: samarth
docker_service_name: "{{ service_odk_uci_adapter_service }}"
force_reload: "{{ force_reload_odk_uci_adapter_service }}"
host_logs_location: "{{ odk_uci_adapter_logs }}"
docker_logs_location: /logs

credentials: "{{ lookup('hashi_vault', 'secret={{ odk_uci_adapter_secret_path }}', url=VAULT_ADDR , token=VAULT_TOKEN) }}"