---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_odk_uci_adapter_service }}.yml"
env_file_name: "{{ service_odk_uci_adapter_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: odk_uci_adapter

docker_port: "{{ service_odk_uci_adapter_docker_port }}"
host_port: "{{ service_odk_uci_adapter_host_port }}"
image_name: "{{ image_odk_uci_adapter_service }}"
tag: "{{ tags_odk_uci_adapter_service }}"
replicas: "{{ service_replicas_odk_uci_adapter_service }}"
network_alias_name: "{{ network_alias_odk_uci_adapter_service }}"
docker_service_stack_name: samarth
docker_service_name: "{{ service_odk_uci_adapter_service }}"
force_reload: "{{ force_reload_odk_uci_adapter_service }}"
host_logs_location: "{{ odk_uci_adapter_logs }}"
docker_logs_location: /logs

ODK_UCI_HASURA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
ODK_UCI_UCI_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
ODK_UCI_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
ODK_UCI_HASURA_GRAPHQL_ENABLE_CONSOLE: true
ODK_UCI_UCI_ADAPTER_ID: 4e0c568c-7c42-4f88-b1d6-392ad16b8546
ODK_UCI_HASURA_ADMIN_SECRET: xxx
ODK_UCI_HOLIDAY_TEMPLATE_ID: 1007348367611645936
ODK_UCI_MEETING_TEMPLATE_ID: 1007000306269990204
ODK_UCI_EXAM_ANNOUNCEMENT_TEMPLATE_ID: 1007503502191122960
ODK_UCI_EXAM_RESULT_ANNOUNCEMENT_TEMPLATE_ID: 1007395278815589077
ODK_UCI_ANNOUNCEMENT_TEMPLATE_ID: 1007231728603182191
ODK_UCI_HOMEWORK_TEMPLATE_ID: 1007231728603182191
POSTGRES_USER: xxxx
ODK_UCI_POSTGRES_PASSWORD: xxxx
DATABASE_USER: xxxx
DATABASE_PASSWORD: xxxx

ODK_UCI_REDIS_HOST_URL: xxx
ODK_UCI_REDIS_HOST_PORT: 1122
