---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: stack-proxy
      tags: [stack-proxy]
    - role: deploy-esamwad-backend
      tags: [deploy-esamwad-backend]
    - role: deploy-user-service
      tags: [deploy-user-service]
    - role: deploy-fusion-auth
      tags: [deploy-fusion-auth]
    - role: deploy-yaus-hasura
      tags: [deploy-yaus-hasura]
    - role: deploy-yaus-broker
      tags: [deploy-yaus-broker]
    - role: deploy-yaus-redis-ui
      tags: [deploy-yaus-redis-ui]
    - role: deploy-yaus-web
      tags: [deploy-yaus-web]
    - role: deploy-odk-uci-adapter
      tags: [deploy-odk-uci-adapter]
    - role: deploy-odk
      tags: [deploy-odk]
    - role: deploy-fa-relay
      tags: [deploy-fa-relay]
    - role: deploy-fa-proxy
      tags: [deploy-fa-proxy]
    - role: deploy-cdac-service
      tags: [deploy-cdac-service]
    - role: deploy-fa-captcha-service
      tags: [deploy-fa-captcha-service]
    - role: deploy-doc-generator-hasura
      tags: [deploy-doc-generator-hasura]
    - role: deploy-doc-generator-broker
      tags: [deploy-doc-generator-broker]
    - role: deploy-doc-generator-web
      tags: [deploy-doc-generator-web]
    - role: deploy-doc-generator-worker
      tags: [deploy-doc-generator-worker]
    - role: deploy-templater
      tags: [deploy-templater]
    - role: deploy-posthog-clickhouse
      tags: [deploy-posthog-clickhouse]
    - role: deploy-posthog-kafka
      tags: [deploy-posthog-kafka]
    - role: deploy-posthog-zookeeper
      tags: [deploy-posthog-zookeeper]
    - role: deploy-posthog-object-storage
      tags: [deploy-posthog-object-storage]
    - role: deploy-posthog
      tags: [deploy-posthog]
    - role: deploy-airflow-webserver
      tags: [deploy-airflow-webserver]
    - role: deploy-airflow-flower
      tags: [deploy-airflow-flower]
    - role: deploy-airflow-scheduler
      tags: [deploy-airflow-scheduler]
    - role: deploy-airflow-worker
      tags: [deploy-airflow-worker]
    - role: deploy-minio
      tags: [deploy-minio]
    - role: deploy-sentry
      tags: [deploy-sentry]
    - role: deploy-esamwad-hasura
      tags: [deploy-esamwad-hasura]
    - role: deploy-esamwad-pgbouncer
      tags: [deploy-esamwad-pgbouncer]
    - role: deploy-posthog-db
      tags: [ deploy-posthog-db ]
    - role: deploy-uci-apis
      tags: [ deploy-uci-apis ]
    - role: deploy-uci-fusion-auth
      tags: [ deploy-uci-fusion-auth ]
    - role: deploy-uci-api-db-hasura
      tags: [ deploy-uci-api-db-hasura ]