---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_templater_service }}.yml"
env_file_name: "{{ service_templater_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: templater_service


docker_port: "{{ service_templater_docker_port }}"
host_port: "{{ service_templater_host_port }}"
image_name: "{{ image_templater_service }}"
tag: "{{ tags_templater_service }}"
replicas: "{{ service_replicas_templater_service }}"
network_alias_name: "{{ network_alias_templater_service }}"
docker_service_stack_name: samarth
docker_service_name: "{{ service_templater_service }}"
force_reload: "{{ force_reload_templater_service }}"
host_logs_location: "{{ templater_logs }}"
docker_logs_location: /logs

DOCKER_HUB_IMAGE: samagragovernance/templater:{{ tag }}
# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ templater_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"