---
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}_cron
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}_worker
    when: "force_reload==true"
    ignore_errors: true