---
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}
    when: "force_reload==true"
    ignore_errors: true
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}_gql
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}_gql
    when: "force_reload==true"
    ignore_errors: true
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}_redis-ui
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}_redis-ui
    when: "force_reload==true"
    ignore_errors: true