---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_fa_relay_service }}.yml"
env_file_name: "{{ service_fa_relay_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: fa-relay-service


docker_port: "{{ service_fa_relay_docker_port }}"
host_port: "{{ service_fa_relay_host_port }}"
image_name: "{{ image_fa_relay_service }}"
tag: "{{ tags_fa_relay_service }}"
replicas: "{{ service_replicas_fa_relay_service }}"
network_alias_name: "{{ network_alias_fa_relay_service }}"
docker_service_stack_name: samarth
docker_service_name: "{{ service_fa_relay_service }}"
force_reload: "{{ force_reload_fa_relay_service }}"
host_logs_location: "{{ fa_relay_logs }}"
docker_logs_location: /logs

credentials: "{{ lookup('hashi_vault', 'secret={{ fa_relay_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"

CORS_ORIGIN: "{{ credentials.CORS_ORIGIN }}"
PORT: "{{ docker_port }}"