---
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}
    when: "force_reload==true"
    ignore_errors: true
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}_zookeeper
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}_zookeeper
    when: "force_reload==true"
    ignore_errors: true
  - name: Removing the existing service {{  docker_service_stack_name  }}_{{ docker_service_name }}_kafka
    shell: docker service rm {{  docker_service_stack_name  }}_{{ docker_service_name }}_kafka
    when: "force_reload==true"
    ignore_errors: true